export const wilayas = [
  { id: "1", name: "Adrar", communes: ["Adrar", "Fenoughil", "Reggane", "Aoulef"] },
  { id: "2", name: "Chlef", communes: ["Chlef", "Ténès", "Ouled Fares", "Boukadir"] },
  { id: "3", name: "Laghouat", communes: ["Laghouat", "Aflou", "Ain Madhi", "Hassi R'Mel"] },
  { id: "4", name: "Oum El Bouaghi", communes: ["Oum El Bouaghi", "Ain Beida", "Ain M'lila", "Aih Kercha"] },
  { id: "5", name: "Batna", communes: ["Batna", "Arris", "Barika", "Merouana"] },
  { id: "6", name: "Béjaïa", communes: ["Béjaïa", "Amizour", "Akbou", "El Kseur"] },
  { id: "7", name: "Biskra", communes: ["Biskra", "Tolga", "Ouled Djellal", "Sidi Okba"] },
  { id: "8", name: "Béchar", communes: ["Béchar", "Kenadsa", "Abadla", "Taghit"] },
  { id: "9", name: "Blida", communes: ["Blida", "Boufarik", "Beni Mered", "Ouled Yaich"] },
  { id: "10", name: "Bouira", communes: ["Bouira", "Lakhdaria", "Sour El Ghozlane", "Ain Bessem"] },
  { id: "11", name: "Tamanrasset", communes: ["Tamanrasset", "In Salah", "In Amguel", "Idles"] },
  { id: "12", name: "Tébessa", communes: ["Tébessa", "Bir El Ater", "Cheria", "Ouenza"] },
  { id: "13", name: "Tlemcen", communes: ["Tlemcen", "Maghnia", "Ghazaouet", "Remchi"] },
  { id: "14", name: "Tiaret", communes: ["Tiaret", "Frenda", "Sougueur", "Ksar Chellala"] },
  { id: "15", name: "Tizi Ouzou", communes: ["Tizi Ouzou", "Azazga", "Draâ Ben Khedda", "Larbaâ Nath Irathen"] },
  { id: "16", name: "Alger", communes: ["Alger Centre", "Sidi M'Hamed", "Bab El Oued", "Boussaada", "Kouba", "El Harrach", "Dely Ibrahim"] },
  { id: "17", name: "Djelfa", communes: ["Djelfa", "Hassi Bahbah", "Ain Oussera", "Messaad"] },
  { id: "18", name: "Jijel", communes: ["Jijel", "Taher", "El Milia", "Chekfa"] },
  { id: "19", name: "Sétif", communes: ["Sétif", "El Eulma", "Ain Arnat", "Ain Oulmene"] },
  { id: "20", name: "Saïda", communes: ["Saïda", "Ain El Hadjar", "Youb", "Hassasna"] },
  { id: "21", name: "Skikda", communes: ["Skikda", "El Harrouch", "Azzaba", "Collo"] },
  { id: "22", name: "Sidi Bel Abbès", communes: ["Sidi Bel Abbès", "Tessala", "Sidi Lahcene", "Mostefa Ben Brahim"] },
  { id: "23", name: "Annaba", communes: ["Annaba", "El Bouni", "Sidi Amar", "Berrahal"] },
  { id: "24", name: "Guelma", communes: ["Guelma", "Oued Zenati", "Bouchegouf", "Héliopolis"] },
  { id: "25", name: "Constantine", communes: ["Constantine", "El Khroub", "Hamma Bouziane", "Didouche Mourad"] },
  { id: "26", name: "Médéa", communes: ["Médéa", "Ksar El Boukhari", "Beni Slimane", "Berrouaghia"] },
  { id: "27", name: "Mostaganem", communes: ["Mostaganem", "Ain Tedles", "Bouguirat", "Sidi Ali"] },
  { id: "28", name: "M'Sila", communes: ["M'Sila", "Bou Saâda", "Sidi Aissa", "Magra"] },
  { id: "29", name: "Mascara", communes: ["Mascara", "Sig", "Mohammadia", "Ghriss"] },
  { id: "30", name: "Ouargla", communes: ["Ouargla", "Hassi Messaoud", "Rouissat", "Ain Beida"] },
  { id: "31", name: "Oran", communes: ["Oran", "Arzew", "Es Senia", "Bir El Djir", "Ain El Turk"] },
  { id: "32", name: "El Bayadh", communes: ["El Bayadh", "Bougtob", "El Abiodh Sidi Cheikh", "Brezina"] },
  { id: "33", name: "Illizi", communes: ["Illizi", "Djanet", "In Amenas", "Bordj Omar Driss"] },
  { id: "34", name: "Bordj Bou Arréridj", communes: ["Bordj Bou Arréridj", "Ras El Oued", "Mansoura", "Medjana"] },
  { id: "35", name: "Boumerdès", communes: ["Boumerdès", "Dellys", "Boudouaou", "Khemis El Khechna"] },
  { id: "36", name: "El Tarf", communes: ["El Tarf", "El Kala", "Dréan", "Besbes"] },
  { id: "37", name: "Tindouf", communes: ["Tindouf", "Oum El Assel"] },
  { id: "38", name: "Tissemsilt", communes: ["Tissemsilt", "Theniet El Had", "Lardjem", "Khemisti"] },
  { id: "39", name: "El Oued", communes: ["El Oued", "Guemar", "Debila", "Robbah"] },
  { id: "40", name: "Khenchela", communes: ["Khenchela", "Kais", "Ais El Beida", "Bouhmama"] },
  { id: "41", name: "Souk Ahras", communes: ["Souk Ahras", "Sedrata", "M'daourouch", "Taoura"] },
  { id: "42", name: "Tipaza", communes: ["Tipaza", "Cherchell", "Kolea", "Hadjout"] },
  { id: "43", name: "Mila", communes: ["Mila", "Chelghoum Laid", "Ferdjioua", "Grarem Gouga"] },
  { id: "44", name: "Aïn Defla", communes: ["Aïn Defla", "Khemis Miliana", "Miliana", "El Attaf"] },
  { id: "45", name: "Naâma", communes: ["Naâma", "Mecheria", "Ain Sefra"] },
  { id: "46", name: "Aïn Témouchent", communes: ["Aïn Témouchent", "Beni Saf", "Hammam Bou Hadjar", "El Amria"] },
  { id: "47", name: "Ghardaïa", communes: ["Ghardaïa", "Metlili", "El Guerrara", "Bounoura"] },
  { id: "48", name: "Relizane", communes: ["Relizane", "Oued Rhiou", "Mazouna", "Ammi Moussa"] },
  { id: "49", name: "El M'Ghair", communes: ["El M'Ghair", "Djamaa"] },
  { id: "50", name: "El Menia", communes: ["El Menia", "Hassi Gara"] },
  { id: "51", name: "Ouled Djellal", communes: ["Ouled Djellal", "Sidi Khaled"] },
  { id: "52", name: "Bordj Baji Mokhtar", communes: ["Bordj Baji Mokhtar", "Timiaouine"] },
  { id: "53", name: "Béni Abbès", communes: ["Béni Abbès", "Taghit", "Kerzaz"] },
  { id: "54", name: "Timimoun", communes: ["Timimoun", "Aoulef"] },
  { id: "55", name: "Touggourt", communes: ["Touggourt", "Nezla", "Tebesbest"] },
  { id: "56", name: "Djanet", communes: ["Djanet", "Bordj El Haouas"] },
  { id: "57", name: "In Salah", communes: ["In Salah", "Foggaret Ezzaouia"] },
  { id: "58", name: "In Guezzam", communes: ["In Guezzam", "Tin Zaouatine"] },
];
